name: folderslint
description: Directory structure linter for Front-End projects.
version: 1.0.2
repository: https://github.com/Takin-Profit/folderslint.dart
homepage: https://github.com/Takin-Profit/folderslint.dart

environment:
  sdk: ^3.0.0

executables:
  folderslint:
# Add regular dependencies here.
dependencies:
  chalkdart: ^2.0.9
  glob: ^2.1.2
  path: ^1.8.3

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.3
