name: folderslint
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  chalkdart: ^2.0.9
  glob: ^2.1.2
  path: ^1.8.3

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.3
